# Initail state of the FSM
initial_state: "JOYSTICK_CONTROL"

events: #Maps from subscribing topic to signal ids
  yourturn: 
    topic: "stop_line_filter_node/send"
    msg_type: "BoolStamped"
    trigger: True
  joystick_override_on: 
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: True
  pressA: 
    topic: "joy_mapper_node/press_A"
    msg_type: "BoolStamped"
    trigger: True
  pressB: 
    topic: "joy_mapper_node/press_B"
    msg_type: "BoolStamped"
    trigger: True
  pressY:
    topic: "joy_mapper_node/press_Y"
    msg_type: "BoolStamped"
    trigger: True
  notpressY:
    topic: "joy_mapper_node/press_Y"
    msg_type: "BoolStamped"
    trigger: False
  joystick_override_off: 
    topic: "joy_mapper_node/joystick_override"
    msg_type: "BoolStamped"
    trigger: False
  at_stop_line:
    topic: "stop_line_filter_node/at_stop_line"
    msg_type: "BoolStamped"
    trigger: True

# Define global transitions. Available from all states.
global_transitions:
  joystick_override_on: "JOYSTICK_CONTROL"
  parallel_autonomy_on: "PARALLEL_AUTONOMY"
  parallel_autonomy_off: "JOYSTICK_CONTROL"

# Define nodes 
nodes:
  decoder_node: "decoder_node/switch"
# anti_instagram_node: "anti_instagram/switch"
  apriltag_node: "apriltag_detector_node/switch"
  line_detector_node: "line_detector_node/switch"
  lane_filter_node: "lane_filter_node/switch"
  stop_line_filter_node: "stop_line_filter_node/switch"
  stop_line_filter_node_fsm: "stop_line_filter_node_fsm/switch"
  framerate_high: "camera_node/framerate_high_switch"

# Define state transitions
states:
  JOYSTICK_CONTROL:
    transitions:
      pressA: "JOYSTICK_CONTROL"
      #pressB: "LANE_FOLLOWING"
      #yourturn: "LANE_FOLLOWING"
      notpressY: "JOYSTOP"
#      pressX: "CAR13"
#      pressY: "CAR14"
#      at_stop_line: "LANE_FOLLOWING"
#      joystick_override_off: "LANE_FOLLOWING"
#      start_avoidance: "LANE_FOLLOWING_AVOID"
    active_nodes:
      - lane_filter_node
      - line_detector_node
      - framerate_high
      - decoder_node
      - apriltag_node
    lights: ["joystick"]   
  JOYSTOP:
    transitions:
      pressA: "JOYSTICK_CONTROL"
      #pressB: "LANE_FOLLOWING"
      #yourturn: "LANE_FOLLOWING"
#      pressX: "CAR13"
      pressY: "JOYSTICK_CONTROL"
#      at_stop_line: "LANE_FOLLOWING"
#      joystick_override_off: "LANE_FOLLOWING"
#      start_avoidance: "LANE_FOLLOWING_AVOID"
    active_nodes:
      - lane_filter_node
      - line_detector_node
      - framerate_high
      - decoder_node
      - apriltag_node
    lights: ["joystick"]   